name: Copying files to EC2
on:
  push:
    paths:
      - 'py_scripts/**'
jobs:
  copy-scripts-to-EC2:
    name: Copy Files to EC2
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository to EC2 instance and Copy Script to python env
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.SSH_HOST_NAME }}
          username: ${{ secrets.SSH_USER_NAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Check if Git is installed
            if ! command -v git &> /dev/null; then
              echo "Git not found. Installing Git..."
              sudo apt install -y git
            else
              echo "Git is already installed."
            fi

            # Check if the directory exists and remove it
            if [ -d "/home/ubuntu/code_repo/Wealthwise" ]; then
              echo "Directory exists. Removing it..."
              sudo rm -rf /home/ubuntu/code_repo/Wealthwise
            fi

            # Create directory and clone the repository
            mkdir -p /home/ubuntu/code_repo/Wealthwise
            echo "Cloning repository..."
            git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ github.repository }} /home/ubuntu/code_repo/Wealthwise

            # Copy py_scripts to the python environment directory
            cp -r /home/ubuntu/code_repo/Wealthwise/py_scripts/* /home/ubuntu/py-venv/

            # Kill existing Streamlit processes on specified ports
            lsof -t -i :8501 -i :8503 -i :8504 -i :8507 | xargs -r kill -9 #-i :8505 -i :8506

            # Activate Python environment once
            source /home/ubuntu/py-venv/bin/activate 
            cd /home/ubuntu/py-venv/

            nohup streamlit run /home/ubuntu/py-venv/elliot_wave.py > /dev/null 2> error.log & #--server.fileWatcherType polling 300000
            nohup streamlit run /home/ubuntu/py-venv/elliot_wave_30min.py --server.port 8503 > /dev/null 2> error_ew_30min.log & #--server.fileWatcherType polling 300000
            nohup streamlit run /home/ubuntu/py-venv/elliot_wave_1h.py --server.port 8504 > /dev/null 2> error_ew_1h.log & #--server.fileWatcherType polling 300000
            # nohup streamlit run /home/ubuntu/py-venv/elliot_wave_5min.py --server.port 8505 > /dev/null 2> error_ew_5m.log &
            # nohup streamlit run /home/ubuntu/py-venv/elliot_wave_10min.py --server.port 8506 > /dev/null 2> error_ew_10m.log &
            nohup streamlit run /home/ubuntu/py-venv/elliot_wave_15min.py --server.port 8507 > /dev/null 2> error_ew_15m.log & #--server.fileWatcherType polling 300000
            echo "Streamlit app deployed and running in the background."