#TRADE VALUES
PROFIT_FOR_ONE_POINT = 50
PERFORM_TRADING_USA = 1
PERFORM_TRADING_ASIA = 0
PERFORM_TRADING_EUROPE = 0


#TIMINGS FOR DIFFERENT MARKETS
EUROPE_MARKET_START_TIME = '00:00'
EUROPE_MARKET_END_TIME = '06:59'
USA_MARKET_START_TIME = '09:30'
USA_MARKET_END_TIME = '15:45'
ASIA_MARKET_START_TIME = '18:00'
ASIA_MARKET_END_TIME = '23:59'

